version: "3.7"

services:
  franzible:
    image: bewr42/franzible_nuxt-app:v0.1
    restart: always
    container_name: "franzible"
    hostname: "franzible"
#    ports: 
#      - 8050:80
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.franzible.entrypoints=websecure"
          - "traefik.http.routers.franzible.rule=Host(`franzible.$MY_DOMAIN`)"
          - "traefik.http.routers.franzible.tls.certresolver=lets-encr"
          - "traefik.http.services.franzible.loadbalancer.server.port=80"
    links:
      - "franzible_feather-app:api"
    environment:
      NODE_ENV: production

  franzible_feather-app:
    image: bewr42/franzible_feather-app:v0.1
    depends_on:
      - franzible_mongo-db
    restart: always
    environment:
      NODE_ENV: production
      PORT: "80"
      MONGOHQ_URL: "mongodb://db:27017/franzible"
      MEDIA_PATH: "/mnt/media"
      AUTH_SECRET: "$FRANZIBLE_AUTH_SECRET"
      AUDIENCE: "$FRANZIBLE_DOMAIN"
    links:
      - "franzible_mongo-db:db"
    volumes:
      - $FRANZIBLE_MEDIA_PATH:/mnt/media

  franzible_mongo-db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - $FRANZIBLE_DB_FOLDER:/data/db
    restart: always
    # Uncomment to change startup options
    environment:
      #  MONGO_INITDB_ROOT_USERNAME: root
      #  MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: franzible

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

networks:
  default:
    external:
      name: $DEFAULT_NETWORK